# Site settings
title: 
header-img: img/home-bg.png
email: rich@cityofla.net
copyright_name: cityofla
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: codingreport
github_username:  cityofla
learn_profile: cityofla
email_username: rich@cityofla.net

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
